//
//  ieEnums.h
//  ieCore
//
//  Created by sergey.sergeev on 2/5/14.
//  Copyright (c) 2014 Sergey Sergeev. All rights reserved.
//

#ifndef ieCore_ieEnums_h
#define ieCore_ieEnums_h

enum E_PLATFORM_API
{
    E_PLATFORM_API_IOS = 0,
    E_PLATFORM_API_WIN32,
    E_PLATFORM_API_OSX,
    E_PLATFORM_API_NDK
};

enum E_VALUE_TYPE
{
    E_VALUE_TYPE_BOOL = 0,
    E_VALUE_TYPE_I8,
    E_VALUE_TYPE_UI8,
    E_VALUE_TYPE_I16,
    E_VALUE_TYPE_UI16,
    E_VALUE_TYPE_I32,
    E_VALUE_TYPE_UI32,
    E_VALUE_TYPE_F32,
    E_VALUE_TYPE_MAX
};

enum E_SHADER_ATTRIBUTE
{
    E_SHADER_ATTRIBUTE_POSITION = 0,
    E_SHADER_ATTRIBUTE_TEXCOORD,
    E_SHADER_ATTRIBUTE_COLOR,
    E_SHADER_ATTRIBUTE_MAX
};

enum E_SHADER_UNIFORM
{
    E_SHADER_UNIFORM_MATRIX_WORLD = 0,
    E_SHADER_UNIFORM_MATRIX_VIEW,
    E_SHADER_UNIFORM_MATRIX_PROJECTION,
    E_SHADER_UNIFORM_VECTOR_CAMERA_POSITION,
    E_SHADER_UNIFORM_MAX
};

enum E_SHADER_SAMPLER
{
    E_SHADER_SAMPLER_01 = 0,
    E_SHADER_SAMPLER_02,
    E_SHADER_SAMPLER_03,
    E_SHADER_SAMPLER_04,
    E_SHADER_SAMPLER_05,
    E_SHADER_SAMPLER_06,
    E_SHADER_SAMPLER_07,
    E_SHADER_SAMPLER_08,
    E_SHADER_SAMPLER_MAX
};

enum E_UNIFORM_CLASS
{
    E_UNIFORM_CLASS_MAT3X3 = 0,
    E_UNIFORM_CLASS_MAT4X4,
    E_UNIFORM_CLASS_VECTOR2,
    E_UNIFORM_CLASS_VECTOR3,
    E_UNIFORM_CLASS_VECTOR4,
    E_UNIFORM_CLASS_FLOAT,
    E_UNIFORM_CLASS_INT,
    E_UNIFORM_CLASS_SAMPLER
};

enum E_RESOURCE_TYPE
{
    E_RESOURCE_TYPE_SHADER = 0,
    E_RESOURCE_TYPE_TEXTURE,
    E_RESOURCE_TYPE_SEQUENSE
};

#endif
